version: 2
jobs:
  build:
    working_directory: ~/taxiapi
    docker:
      - image: circleci/node:10-browsers
        environment:
          NODE_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:5432/taxidb"
          JWT_SECRET: "foobarfoobar"
          REALTIMEDATABASE_URL: "ws://localhost:5000"
      - image: circleci/postgres:10-alpine-postgis-ram

    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Instal dependencies
          command: npm install
      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: setup
          command: |
            createdb taxidb
            npx knex migrate
      - run:
          name: Test
          command: |
            npm test --ci --coverage --maxWorkers 2
            npx firebase-server -p 5000 -e -b && npx wait-on http://localhost:5000
            npm start & npx wait-on http://localhost:3000
            npx cypress run
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: junit.xml
